name: $(major).$(minor).$(revision)$(Rev:.r)
trigger:
- main

variables:
  agentSolution: 'src/Agent.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  major: 6
  minor: 0
  revision: 0
  fileVersion: '$(Build.BuildNumber)'

jobs:
- job: build
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: DownloadSecureFile@1
    displayName: 'Download Signing Key'  
    name: loupeAgentSigningKey
    inputs:
      secureFile: 'loupe.agent.snk'

  - task: DownloadSecureFile@1
    displayName: 'Download Code Signing Cert'  
    name: GibraltarSoftwareCCC
    inputs:
      secureFile: 'GibraltarSoftwareCCC.pfx'
      overWrite: true

  - task: CopyFiles@2
    displayName: 'Copy Signing Key to Build Location'  
    inputs:
      SourceFolder: '$(Agent.TempDirectory)'
      Contents: 'loupe.agent.snk'
      TargetFolder: '$(Build.SourcesDirectory)'
      overWrite: true

  - task: UseDotNet@2
    displayName: 'Install .NET 6 (for test running)'
    inputs:
      version: '6.0.x'

  - task: UseDotNet@2
    displayName: 'Install .NET 8 (for building)'
    inputs:
      version: '8.0.x'

  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    displayName: 'Restore NuGet Packages'  
    inputs:
      restoreSolution: '$(agentSolution)'

  - task: VSBuild@1
    displayName: 'Build NuGet Packages'  
    inputs:
      solution: '$(agentSolution)'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
      msbuildArgs: '/p:CustomVersion=$(fileVersion) /p:CustomInformationalVersion=$(fileVersion) /p:PackageVersion=$(fileVersion)'

  - task: CopyFiles@2
    displayName: 'Stage NuGet Packages'  
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)/src'
      contents: '**/*.*nupkg'
      flattenFolders: true
      targetFolder: '$(Build.ArtifactStagingDirectory)/packages'

  - task: NuGetCommand@2
    displayName: 'Sign NuGet Packages'  
    inputs:
      command: 'custom'
      arguments: sign $(Build.ArtifactStagingDirectory)\packages\*.nupkg -CertificatePath $(Agent.TempDirectory)/GibraltarSoftwareCCC.pfx -CertificatePassword f4rd+GM% -Timestamper http://timestamp.comodoca.com -Verbosity detailed

  - task: NuGetCommand@2
    displayName: 'Sign NuGet Symbol Packages'  
    inputs:
      command: 'custom'
      arguments: sign $(Build.ArtifactStagingDirectory)\packages\*.snupkg -CertificatePath $(Agent.TempDirectory)/GibraltarSoftwareCCC.pfx -CertificatePassword f4rd+GM% -Timestamper http://timestamp.comodoca.com -Verbosity detailed

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)/packages'
      artifactName: packages

  - task: NuGetAuthenticate@0
    displayName: 'Authenticate with NuGet feed'

  - task: NuGetCommand@2
    displayName: 'Push NuGet Packages to Feed'
    condition: eq(variables['Build.Reason'], 'IndividualCI')
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/packages/*.nupkg'
      publishVstsFeed: 'private-nuget'
      allowPackageConflicts: true

  - task: VSTest@2
    inputs:
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
      testSelector: 'testAssemblies'
      testAssemblyVer2: |
        **/bin/Release/**/*.Test.dll
        **/bin/Release/**/*.Tests.dll
        !EntityFramework.Tests.dll
      searchFolder: '$(Build.SourcesDirectory)'
      vsTestVersion: 'latest'
      codeCoverageEnabled: true