using System;

namespace Loupe.Extensibility.Data
{
    /// <summary>
    /// A textual comment added to an issue.
    /// </summary>
    public interface IIssueNote
    {
        /// <summary>
        /// The unique key for this note
        /// </summary>
        Guid Id { get; }

        /// <summary>
        /// The order of this note within the issue
        /// </summary>
        int Sequence { get; }

        /// <summary>
        /// The full note text
        /// </summary>
        /// <remarks>Not limited in length.</remarks>
        string Note { get; }

        /// <summary>
        /// The user that added this note
        /// </summary>
        /// <remarks>The LocalSystem user is used for system-generated notes</remarks>
        IUserProfile AddedBy { get; }

        /// <summary>
        /// The timestamp when this note was added.
        /// </summary>
        DateTimeOffset AddedTimestamp { get; }

        /// <summary>
        /// The issue this note is related to
        /// </summary>
        IIssue Issue { get; }

        /// <summary>
        /// Indicates if a note was generated by the system or a user.
        /// </summary>
        IssueNoteCategory Category { get; }
    }
}
