namespace Loupe.Extensibility.Data
{
    /// <summary>
    /// The category of a note on an issue to help format and display notes.
    /// </summary>
    public enum IssueNoteCategory
    {
        /// <summary>
        /// The note category was not specified.
        /// </summary>
        /// <remarks>This value shouldn't occur in a running system</remarks>
        Unknown = 0,

        /// <summary>
        /// The note was generated by the system itself
        /// </summary>
        System = 1,

        /// <summary>
        /// The note was generated by a user.
        /// </summary>
        User = 2
    }
}
