using System;
using System.Globalization;

namespace Loupe
{
    /// <summary>
    /// This exception indicates that an unexpected packet version was encountered.
    /// </summary>
    /// <remarks>This exception occurs when processing a Loupe log packet with a version
    /// which is not understood by this version of Loupe.  This usually means that an older
    /// version of Loupe is trying to read a log stream generated by a newer and incompatible
    /// version of Loupe.  For more information, see the root class, Exception.</remarks>
    public class LoupePacketVersionException : LoupeException
    {

        /// <summary>
        /// Initializes a new instance of the LoupePacketVersionException class.
        /// </summary>
        /// <remarks>This constructor initializes the Message property of the new instance to a system-supplied
        /// message that describes the error and takes into account the current system culture.
        /// For more information, see the base constructor in Exception.</remarks>
        public LoupePacketVersionException()
        {
            // Just the base default constructor
        }

        /// <summary>
        /// Initializes a new instance of the LoupePacketVersionException class with a specified error message.
        /// </summary>
        /// <param name="message">The error message string.</param>
        /// <remarks>This constructor initializes the Message property of the new instance using the
        /// message parameter.  The InnerException property is left as a null reference.
        /// For more information, see the base constructor in Exception.</remarks>
        public LoupePacketVersionException(string message)
            : base(message)
        {
            // Just the base constructor
        }

        /// <summary>
        /// Initializes a new instance of the LoupePacketVersionException class with a specified error message
        /// and a reference to the inner exception that is the cause of this exception.
        /// </summary>
        /// <param name="message">The error message string.</param>
        /// <param name="innerException">The exception that is the cause of the current exception, or a
        /// null reference if no inner exception is specified.</param>
        /// <remarks>An exception that is thrown as a direct result of a previous exception should include
        /// a reference to the previous exception in the innerException parameter.
        /// For more information, see the base constructor in Exception.</remarks>
        public LoupePacketVersionException(string message, Exception innerException)
            : base(message, innerException)
        {
            // Just the base constructor
        }

        /// <summary>
        /// Initializes a new instance of the LoupePacketVersionException class to a standard
        /// error message string given a supplied version parameter.
        /// </summary>
        /// <param name="version">The unexpected version encountered</param>
        /// <remarks>This is the preferred way to initialize this exception type, because
        /// this constructor automatically formats the message string to be "Unexpected version: {0}",
        /// where {0} is replaced with the provided version argument.</remarks>
        public LoupePacketVersionException(int version)
            : this(string.Format(CultureInfo.InvariantCulture, "Unexpected version: {0}", version))
        {
            // Just call the other constructor
        }
    }
}